- name: Install f2b
  apt:
    name=fail2ban
    state=present

- name: Template f2b config
  template:
    src: jail.conf.j2
    dest: /etc/fail2ban/jail.conf
  become: yes

- name: Start and enable f2b
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes